import type {
  ActId,
  ActReaction,
  CategoryId,
  CategoryPreset,
  MemePreset,
  MoveDef,
  RageLevel,
  SceneInfo,
} from "./types";

export const CATEGORIES: CategoryPreset[] = [
  {
    id: "boss",
    label: "Boss",
    name: "Boss",
    shirt: "#c0392b",
    hair: "#111111",
    skin: "#c9956c",
    vibe: "smug",
    hairStyle: "short",
    body: "avg",
    scene: "office",
  },
  {
    id: "ex",
    label: "Ex",
    name: "Ex",
    shirt: "#9b59b6",
    hair: "#3d2314",
    skin: "#d4a574",
    vibe: "fancy",
    hairStyle: "long",
    body: "slim",
    scene: "bedroom",
  },
  {
    id: "friend",
    label: "Friend",
    name: "Friend",
    shirt: "#3498db",
    hair: "#1c1410",
    skin: "#c9956c",
    vibe: "smug",
    hairStyle: "messy",
    body: "avg",
    scene: "street",
  },
  {
    id: "teacher",
    label: "Teacher",
    name: "Teacher",
    shirt: "#2c3e50",
    hair: "#555555",
    skin: "#d4a574",
    vibe: "nerdy",
    hairStyle: "short",
    body: "avg",
    scene: "classroom",
  },
  {
    id: "politician",
    label: "Politician",
    name: "Politician",
    shirt: "#1a365d",
    hair: "#1a1a1a",
    skin: "#c9956c",
    vibe: "fancy",
    hairStyle: "short",
    body: "stocky",
    scene: "office",
  },
  {
    id: "influencer",
    label: "Influencer",
    name: "Influencer",
    shirt: "#e91e8c",
    hair: "#111111",
    skin: "#d4a574",
    vibe: "fancy",
    hairStyle: "messy",
    body: "slim",
    scene: "street",
  },
  {
    id: "coworker",
    label: "Coworker",
    name: "Coworker",
    shirt: "#5dade2",
    hair: "#4a3728",
    skin: "#c9956c",
    vibe: "smug",
    hairStyle: "buzz",
    body: "avg",
    scene: "office",
  },
  {
    id: "family",
    label: "Family",
    name: "Family",
    shirt: "#27ae60",
    hair: "#2c1810",
    skin: "#d4a574",
    vibe: "angry",
    hairStyle: "short",
    body: "stocky",
    scene: "bedroom",
  },
  {
    id: "fictional",
    label: "Fictional",
    name: "Villain",
    shirt: "#8e44ad",
    hair: "#000000",
    skin: "#c9956c",
    vibe: "angry",
    hairStyle: "long",
    body: "avg",
    scene: "street",
  },
  {
    id: "custom",
    label: "Custom",
    name: "Nemesis",
    shirt: "#c0392b",
    hair: "#111111",
    skin: "#c9956c",
    vibe: "smug",
    hairStyle: "short",
    body: "avg",
    scene: "office",
  },
];

export const SCENES: SceneInfo[] = [
  { id: "office", label: "Office", blurb: "Meetings never end" },
  { id: "classroom", label: "Classroom", blurb: "Pop quiz energy" },
  { id: "street", label: "Street", blurb: "Traffic & chaos" },
  { id: "bedroom", label: "Bedroom", blurb: "Private rage room" },
];

export const MEMES: MemePreset[] = [
  {
    id: "monday",
    label: "Monday",
    blurb: "Destroy Monday Morning",
    name: "Monday",
    shirt: "#34495e",
    hair: "#1a1a1a",
    skin: "#c9956c",
    vibe: "angry",
    hairStyle: "messy",
    body: "stocky",
    face: "square",
    accessory: "none",
    shoes: "boots",
    expression: "frown",
    scene: "office",
    lines: ["It's only Monday.", "Alarm clock energy.", "Coffee won't save you.", "Weekend who?"],
  },
  {
    id: "wifi",
    label: "WiFi",
    blurb: "Router of doom",
    name: "WiFi",
    shirt: "#1abc9c",
    hair: "#111",
    skin: "#d4a574",
    vibe: "smug",
    hairStyle: "buzz",
    body: "slim",
    face: "soft",
    accessory: "headphones",
    shoes: "sneakers",
    expression: "smirk",
    scene: "bedroom",
    lines: ["One bar left.", "Reconnecting…", "Password incorrect.", "Buffering forever."],
  },
  {
    id: "exams",
    label: "Exams",
    blurb: "Results day dread",
    name: "Exams",
    shirt: "#2980b9",
    hair: "#333",
    skin: "#c9956c",
    vibe: "nerdy",
    hairStyle: "short",
    body: "avg",
    face: "round",
    accessory: "glasses",
    shoes: "sneakers",
    expression: "frown",
    scene: "classroom",
    lines: ["Show your work.", "Time's up.", "Multiple choice pain.", "Curve? What curve?"],
  },
  {
    id: "traffic",
    label: "Traffic",
    blurb: "Gridlock rage",
    name: "Traffic",
    shirt: "#e67e22",
    hair: "#222",
    skin: "#d4a574",
    vibe: "angry",
    hairStyle: "buzz",
    body: "stocky",
    face: "square",
    accessory: "hat",
    shoes: "boots",
    expression: "frown",
    scene: "street",
    lines: ["Honk honk.", "Merge properly!", "Red light again.", "ETA: unknown."],
  },
  {
    id: "salary",
    label: "Salary",
    blurb: "Payday vs bills",
    name: "Salary Day",
    shirt: "#27ae60",
    hair: "#1c1410",
    skin: "#c9956c",
    vibe: "fancy",
    hairStyle: "short",
    body: "avg",
    face: "round",
    accessory: "glasses",
    shoes: "boots",
    expression: "smirk",
    scene: "office",
    lines: ["Taxes first.", "Direct deposit delayed.", "Bonus? Cute.", "Rent ate me."],
  },
  {
    id: "internet",
    label: "Internet",
    blurb: "When everything dies",
    name: "Internet",
    shirt: "#8e44ad",
    hair: "#000",
    skin: "#d4a574",
    vibe: "smug",
    hairStyle: "messy",
    body: "slim",
    face: "soft",
    accessory: "headphones",
    shoes: "slippers",
    expression: "wink",
    scene: "bedroom",
    lines: ["404 mood.", "Server unavailable.", "Try again later.", "Lag is a lifestyle."],
  },
];

export const BAM: Record<ActId, string[]> = {
  punch: ["POW!", "BAM!", "WHAM!", "THUD!"],
  slap: ["SLAP!", "WHACK!", "SMACK!", "CLAP!"],
  kick: ["BOOT!", "YEET!", "THWACK!", "KAPOW!"],
  mud: ["SPLAT!", "EW!", "GROSS!", "BLEH!"],
  water: ["SPLASH!", "GLUG!", "SOAKED!", "WHOOSH!"],
  pie: ["PIE!", "CREAM!", "FACE!", "HA!"],
  shake: ["RATTLE!", "SHAKE!", "WOAH!", "STOP!"],
  tomato: ["SPLAT!", "JUICY!", "RED!", "TOSS!"],
  uppercut: ["UPPER!", "SKY!", "BOOM!", "LAUNCH!"],
  taunt: ["HAHA!", "COME ON!", "THAT ALL?", "WEAK!"],
  headbutt: ["BONK!", "CLONK!", "HEAD!", "CRACK!"],
  push: ["YEET!", "BACK!", "SHOVE!", "OUT!"],
  hammer: ["SMASH!", "BONK!", "CLANG!", "WHAM!"],
  ultimate: ["NUKE!", "KABOOM!", "RAGE!", "GONE!"],
  fryingpan: ["CLANG!", "PAN!", "SIZZLE!", "DONG!"],
  slipper: ["CHAPPAL!", "THWAP!", "HOME!", "SMACK!"],
  foambat: ["BONK!", "FOAM!", "SOFT!", "THUD!"],
  banana: ["SLIP!", "PEEL!", "WHOOPS!", "SPLATT!"],
  watergun: ["SQUIRT!", "PEW!", "SOAK!", "SPLASH!"],
};

export const FOE_LINES: Record<ActId, string[]> = {
  punch: ["Oof!", "Hey!", "Ow!", "Not the face!"],
  slap: ["How dare you!", "My cheek!", "Rude!", "Watch it!"],
  kick: ["My shin!", "Unfair!", "Owwww!", "I'll sue!"],
  mud: ["My shirt!", "Disgusting!", "You'll pay!", "Mud?!"],
  water: ["I'm drowning!", "Cold!", "Help!", "Blub blub!"],
  pie: ["Cream…", "My dignity!", "Not again!", "Tastes… weird"],
  shake: ["Put me down!", "Dizzy!", "Stop shaking!", "Bleh—"],
  tomato: ["Tomato juice!", "My suit!", "Gross!", "Farm attack?!"],
  uppercut: ["Flying…!", "Gravity?!", "Aaaah!", "Sky is fake!"],
  taunt: ["You're pathetic.", "Is that it?", "Weak.", "Cute."],
  headbutt: ["My skull!", "Stars…", "Unfair!", "Concussion?!"],
  push: ["I'm falling!", "Hands off!", "Whoa—!", "Space!"],
  hammer: ["Not the hammer!", "Illegal!", "Ow ow ow!", "Call HR!"],
  ultimate: ["I resign!", "Too much!", "Mercy!", "System crash!"],
  fryingpan: ["Kitchen crime!", "Hot pan?!", "My ear!", "Breakfast betrayal!"],
  slipper: ["Not the slipper!", "Mom energy!", "Classic!", "Family technique!"],
  foambat: ["That tickled!", "Foam justice!", "Soft but mean!", "Carnival attack!"],
  banana: ["Peel power!", "Comedy death!", "I slipped!", "Fruit violence!"],
  watergun: ["My outfit!", "Pool party?!", "Soaked!", "Unfair range!"],
};

export const HINTS: Record<ActId, string> = {
  punch: "Straight punch — clean and mean.",
  slap: "Open-hand slap. Instant karma.",
  kick: "Boot to the midsection. They fly.",
  mud: "Mud ball. Fashion disaster.",
  water: "Full dunk in the tub.",
  pie: "Classic cream pie to the face.",
  shake: "Grab and rattle like a soda can.",
  tomato: "Market special — ripe and messy.",
  uppercut: "From the floor to the ceiling.",
  taunt: "Talk smack. Fuel the fire.",
  headbutt: "Close-range skull special.",
  push: "Two hands. One shove. Floor optional.",
  hammer: "Giant cartoon hammer. Safety last.",
  ultimate: "Full rage dump. Use when charged.",
  fryingpan: "Unlocked kitchen justice.",
  slipper: "Unlocked household classic.",
  foambat: "Unlocked soft chaos.",
  banana: "Unlocked peel physics.",
  watergun: "Unlocked soaked revenge.",
};

export const ACT_REACTIONS: Record<ActId, ActReaction> = {
  punch: { mood: "hurt", anim: "hit" },
  slap: { mood: "shocked", anim: "spin" },
  kick: { mood: "shocked", anim: "launch", hard: true },
  mud: { mood: "angry", anim: "hit" },
  water: { mood: "scared", anim: "dunk", hard: true },
  pie: { mood: "crying", anim: "hit" },
  shake: { mood: "dizzy", anim: "shake" },
  tomato: { mood: "angry", anim: "hit" },
  uppercut: { mood: "shocked", anim: "upper", hard: true },
  taunt: { mood: "angry", anim: "hit" },
  headbutt: { mood: "dizzy", anim: "hit", hard: true },
  push: { mood: "scared", anim: "fall" },
  hammer: { mood: "shocked", anim: "launch", hard: true },
  ultimate: { mood: "crying", anim: "run", hard: true },
  fryingpan: { mood: "shocked", anim: "spin", hard: true },
  slipper: { mood: "hurt", anim: "hit" },
  foambat: { mood: "dizzy", anim: "hit" },
  banana: { mood: "laughing", anim: "fall" },
  watergun: { mood: "scared", anim: "hit" },
};

export const CATEGORY_IDLE: Record<CategoryId, string[]> = {
  boss: [
    "Let's schedule a meeting about this.",
    "My calendar is blocked.",
    "Did you send the deck?",
    "Synergy!",
  ],
  ex: [
    "I was just about to call you.",
    "We should talk…",
    "It's not you, it's— wait.",
    "Seen my story?",
  ],
  friend: ["Relax bro!", "You good?", "Okay but hear me out…", "Pizza later?"],
  teacher: ["Pop quiz!", "Detention energy.", "Where's your homework?", "Eyes on me."],
  politician: ["No comment.", "For the people!", "Next question.", "Trust the process."],
  influencer: ["Link in bio!", "Don't forget to like…", "Is this content?", "Brand deal?"],
  coworker: ["Can you take this?", "Quick sync?", "Reply-all incoming.", "Slack me."],
  family: ["We need to talk.", "At dinner?!", "Your cousin did better.", "Put that down."],
  fictional: ["You dare oppose me?", "Plot twist!", "Final form!", "Villain monologue…"],
  custom: ["Is that all?", "Try harder.", "Nice try.", "Still standing."],
};

export const MOVES: MoveDef[] = [
  { act: "punch", ico: "👊", name: "Punch", key: "1", unlockAt: 0 },
  { act: "slap", ico: "✋", name: "Slap", key: "2", unlockAt: 0 },
  { act: "kick", ico: "🦵", name: "Kick", key: "3", unlockAt: 0 },
  { act: "headbutt", ico: "🤕", name: "Headbutt", key: "Q", unlockAt: 0 },
  { act: "push", ico: "🫸", name: "Push", key: "W", unlockAt: 0 },
  { act: "hammer", ico: "🔨", name: "Hammer", key: "E", unlockAt: 0 },
  { act: "mud", ico: "🟤", name: "Mud", key: "4", unlockAt: 0 },
  { act: "water", ico: "💧", name: "Dunk", key: "5", unlockAt: 0 },
  { act: "pie", ico: "🥧", name: "Pie", key: "6", unlockAt: 0 },
  { act: "shake", ico: "🫨", name: "Shake", key: "7", unlockAt: 0 },
  { act: "tomato", ico: "🍅", name: "Tomato", key: "8", unlockAt: 0 },
  { act: "uppercut", ico: "💥", name: "Uppercut", key: "9", unlockAt: 0 },
  { act: "taunt", ico: "😤", name: "Taunt", key: "0", unlockAt: 0 },
  { act: "fryingpan", ico: "🍳", name: "Pan", key: "R", unlockAt: 1 },
  { act: "slipper", ico: "🩴", name: "Slipper", key: "T", unlockAt: 2 },
  { act: "foambat", ico: "🏏", name: "Foam Bat", key: "Y", unlockAt: 4 },
  { act: "banana", ico: "🍌", name: "Banana", key: "F", unlockAt: 6 },
  { act: "watergun", ico: "🔫", name: "Water Gun", key: "G", unlockAt: 8 },
];

export const RAGE_THRESHOLDS: Array<{ min: number; level: RageLevel; label: string }> = [
  { min: 80, level: "nuclear", label: "Nuclear" },
  { min: 60, level: "furious", label: "Furious" },
  { min: 40, level: "angry", label: "Angry" },
  { min: 20, level: "annoyed", label: "Annoyed" },
  { min: 0, level: "calm", label: "Calm" },
];

export const CHALLENGE_SECONDS = 20;
export const ULTIMATE_NEED = 100;

export function rageLevelFor(pct: number): { level: RageLevel; label: string } {
  for (const row of RAGE_THRESHOLDS) {
    if (pct >= row.min) return { level: row.level, label: row.label };
  }
  return { level: "calm", label: "Calm" };
}

export function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]!;
}

export function challengePrompt(foeName: string): string {
  return `Vent on ${foeName} as long as you need — hit Done when you feel better.`;
}

export function isMoveUnlocked(act: ActId, sessions: number): boolean {
  const move = MOVES.find((m) => m.act === act);
  return !!move && sessions >= move.unlockAt;
}

export function newlyUnlockedMoves(previous: number, current: number): MoveDef[] {
  return MOVES.filter((m) => m.unlockAt > previous && m.unlockAt <= current);
}
